server:
  port: 8081

# Configuring info endpoint
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    time: "@buildTime@"
    number: "@buildNumber@"

helloservice:
  url: http://localhost:8080

logging:
  level:
#    org.springframework: DEBUG
#    org.springframework.boot: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.apache: INFO
    com.github.sjacek: DEBUG
  file: ./app.log
